language: ruby
sudo: false
cache: bundler

rvm:
  - 2.4.4

env:
  - TRAVIS=ci DB=mysql HANAMI_ENV=test DATABASE_URL="mysql2://root@127.0.0.1:3306/predios_test"

before_script:
before_install:
  - npm i -g npm

script:
  - bundle exec hanami db create
  - bundle exec hanami db migrate
  - COVERALLS=1 bundle exec rspec
  - npm install
  - npm run build

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client

